#!/bin/bash

ABSPATH=$(cd ${0%/*} && echo `pwd`/${0##*/})
CWD=`dirname "$ABSPATH"`

function link {
    srcfile="$CWD/$1"
    destfile="$HOME/"

    ln -sfnv $srcfile $destfile
}

for file in .*; do
    if [ . != $file ] && [ .. != $file ] && [ '.gitignore' != $file ] && [ '.git' != $file ] && [ 'swp' != ${file##*.} ]; then
        #link $file
        echo $file
    fi
done

for file in bin/*; do
    if [ ! -L "$HOME/$file" ]; then
        ln -sfnv "$CWD/$file" "$HOME/$file"
    fi
done
