#!/bin/bash

DIFF=`which diff`
ABSPATH=$(cd ${0%/*} && echo `pwd`/${0##*/})
CWD=`dirname "$ABSPATH"`

function link {
	srcfile="$CWD/$1"
	destfile="$HOME/"

	ln -sfnv $srcfile $destfile
}

for file in .*; do
	if [ . != $file ] && [ .. != $file ]; then
		link $file
	fi
done
